# Generated by Django 4.2.4 on 2024-06-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IELTSSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('button_text', models.CharField(default='About Our Platform', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ielts_images/')),
            ],
        ),
    ]
