# Generated by Django 4.2.4 on 2024-06-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0002_ieltssection'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('paragraph', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='integration_images/')),
            ],
        ),
    ]
