# Generated by Django 4.2.4 on 2024-06-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0003_integrationsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsection',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='integrationsection',
            name='paragraph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
