# Generated by Django 4.2.4 on 2024-06-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0004_alter_integrationsection_heading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBenfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('button_text', models.CharField(default='About Our Platform', max_length=100)),
                ('image', models.ImageField(upload_to='about_us_images/')),
            ],
        ),
    ]
