# Generated by Django 4.2.4 on 2024-06-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0005_indexbenfit'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexDash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='dash_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='indexbenfit',
            name='image',
            field=models.ImageField(upload_to='benfit_images/'),
        ),
    ]
