# Generated by Django 4.2.4 on 2024-06-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0007_sectioncontent_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='pre_images/')),
            ],
        ),
    ]
