# Generated by Django 4.2.4 on 2024-06-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0009_aboutstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutEmpowering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('paragraph', models.TextField(blank=True, null=True)),
                ('application', models.TextField(blank=True, null=True)),
                ('university', models.TextField(blank=True, null=True)),
                ('accomodation', models.TextField(blank=True, null=True)),
                ('social', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_images/')),
            ],
        ),
    ]
