# Generated by Django 4.2.4 on 2024-06-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0012_remove_aboutteammember_paragraph_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('paragraph', models.TextField()),
                ('image', models.ImageField(upload_to='blog_images/')),
            ],
        ),
    ]
