# Generated by Django 4.2.4 on 2024-06-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0013_blogcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('paragraph', models.TextField()),
                ('image', models.ImageField(upload_to='content_images/')),
                ('list_item_1', models.CharField(max_length=200)),
                ('list_item_2', models.CharField(max_length=200)),
                ('list_item_3', models.CharField(max_length=200)),
            ],
        ),
    ]
