# Generated by Django 4.2.4 on 2024-06-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0014_mastercontentsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercontentsection',
            name='list_item_1',
            field=models.CharField(default='Default list item 1', max_length=200),
        ),
        migrations.AlterField(
            model_name='mastercontentsection',
            name='list_item_2',
            field=models.CharField(default='Default list item 2', max_length=200),
        ),
        migrations.AlterField(
            model_name='mastercontentsection',
            name='list_item_3',
            field=models.CharField(default='Default list item 3', max_length=200),
        ),
    ]
