# Generated by Django 4.2.4 on 2024-06-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0015_alter_mastercontentsection_list_item_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MastersResearchProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='program_images/')),
            ],
        ),
        migrations.CreateModel(
            name='MastersTaughtProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='program_images/')),
            ],
        ),
    ]
