# Generated by Django 4.2.4 on 2024-06-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0016_mastersresearchprogram_masterstaughtprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='UgProgramFirst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='ugprogram_images/')),
                ('paragraph', models.TextField()),
            ],
        ),
    ]
