# Generated by Django 4.2.4 on 2024-06-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0017_ugprogramfirst'),
    ]

    operations = [
        migrations.CreateModel(
            name='UgProgramSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='ugprogramsection_images/')),
            ],
        ),
    ]
