# Generated by Django 4.2.4 on 2024-06-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0018_ugprogramsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='UgProgramInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('paragraph', models.TextField()),
                ('button_text', models.CharField(default='UgProgram Platform', max_length=100)),
                ('list_1', models.CharField(default='Default list item 1', max_length=200)),
                ('list_2', models.CharField(default='Default list item 2', max_length=200)),
                ('list_3', models.CharField(default='Default list item 3', max_length=200)),
            ],
        ),
    ]
