# Generated by Django 4.2.4 on 2024-06-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0020_ugprograms'),
    ]

    operations = [
        migrations.CreateModel(
            name='UgImagesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='ugimagesection_images/')),
            ],
        ),
    ]
