# Generated by Django 4.2.4 on 2024-06-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0021_ugimagessection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ugprogramsection',
            name='text',
        ),
        migrations.AddField(
            model_name='ugprogramsection',
            name='image_1',
            field=models.ImageField(default='default_image_1.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='ugprogramsection',
            name='image_2',
            field=models.ImageField(default='default_image_2.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='ugprogramsection',
            name='paragraph',
            field=models.TextField(default='Default paragraph content'),
        ),
        migrations.AddField(
            model_name='ugprogramsection',
            name='paragraph_1',
            field=models.TextField(default='Default paragraph_1 content'),
        ),
        migrations.AddField(
            model_name='ugprogramsection',
            name='paragraph_2',
            field=models.TextField(default='Default paragraph_2 content'),
        ),
        migrations.AlterField(
            model_name='ugprogramsection',
            name='image',
            field=models.ImageField(default='default_image.png', upload_to=''),
        ),
    ]
