# Generated by Django 5.0.4 on 2024-07-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0026_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='scholarship_images/')),
                ('university_image', models.ImageField(blank=True, null=True, upload_to='university_images/')),
                ('eligible_degrees', models.CharField(max_length=255)),
                ('eligible_courses', models.CharField(max_length=255)),
                ('eligible_nationalities', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('funding_type', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('overview', models.TextField()),
                ('country_intakes_details', models.TextField()),
                ('who_can_apply', models.TextField()),
                ('types_of_awards', models.TextField()),
                ('financial_support', models.TextField()),
                ('alumni_stories', models.TextField()),
                ('other_details', models.TextField()),
                ('more_information', models.TextField()),
            ],
        ),
    ]
