# Generated by Django 5.0.3 on 2024-07-09 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0029_userprofile_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('country_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('native_language', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_name', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_issue_location', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_issue_date', models.DateField(blank=True, null=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('permanent_address_country', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_address_1', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_address_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('permanent_address_state', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_address_city', models.CharField(blank=True, max_length=100, null=True)),
                ('current_address_country', models.CharField(blank=True, max_length=100, null=True)),
                ('current_address_1', models.CharField(blank=True, max_length=255, null=True)),
                ('current_address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('current_address_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('current_address_state', models.CharField(blank=True, max_length=100, null=True)),
                ('current_address_city', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
