# Generated by Django 5.0.3 on 2024-07-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0031_academicinterests_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicinterests',
            name='english_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='academicinterests',
            name='other_test',
            field=models.BooleanField(default=False),
        ),
    ]
