# Generated by Django 5.0.3 on 2024-07-10 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0034_travelhistory_visa_countries_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MandatoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_resume', models.FileField(blank=True, null=True, upload_to='documents-mandatory')),
                ('passport_copy', models.FileField(blank=True, null=True, upload_to='documents-mandatory')),
                ('transcript', models.FileField(blank=True, null=True, upload_to='documents-mandatory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NonMandatoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_school_docs', models.FileField(blank=True, null=True, upload_to='documents/nonmandatory/')),
                ('application_screenshots', models.FileField(blank=True, null=True, upload_to='documents/nonmandatory/')),
                ('cas_copy', models.FileField(blank=True, null=True, upload_to='documents/nonmandatory/')),
                ('chat_upload', models.FileField(blank=True, null=True, upload_to='documents/nonmandatory/')),
                ('disability', models.FileField(blank=True, null=True, upload_to='documents/nonmandatory/')),
                ('english_test_result', models.FileField(blank=True, null=True, upload_to='documents/nonmandatory/')),
                ('eu_settle_docs', models.FileField(blank=True, null=True, upload_to='documents/nonmandatory/')),
                ('o_level_docs', models.FileField(blank=True, null=True, upload_to='documents/nonmandatory/')),
                ('other_certificates', models.FileField(blank=True, null=True, upload_to='documents/nonmandatory/')),
                ('others', models.FileField(blank=True, null=True, upload_to='documents/nonmandatory/')),
                ('pg_provisional_degree', models.FileField(blank=True, null=True, upload_to='documents/nonmandatory/')),
                ('portfolio', models.FileField(blank=True, null=True, upload_to='documents/nonmandatory/')),
                ('post_admission_brp', models.FileField(blank=True, null=True, upload_to='documents/nonmandatory/')),
                ('post_admission_tt_receipt', models.FileField(blank=True, null=True, upload_to='documents/nonmandatory/')),
                ('post_admission_visa', models.FileField(blank=True, null=True, upload_to='documents/nonmandatory/')),
                ('reference_letter', models.FileField(blank=True, null=True, upload_to='documents/nonmandatory/')),
                ('statement_of_purpose', models.FileField(blank=True, null=True, upload_to='documents/nonmandatory/')),
                ('ug_provisional_degree', models.FileField(blank=True, null=True, upload_to='documents/nonmandatory/')),
                ('university_application_docs', models.FileField(blank=True, null=True, upload_to='documents/nonmandatory/')),
                ('visa_refusal', models.FileField(blank=True, null=True, upload_to='documents/nonmandatory/')),
                ('work_experience_certificate', models.FileField(blank=True, null=True, upload_to='documents/nonmandatory/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
