# Generated by Django 5.0.3 on 2024-07-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0036_refereedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradditionalinfo',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
