# Generated by Django 5.0.3 on 2024-07-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0041_alter_mandatorydocument_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='scholarship_logos/'),
        ),
    ]
