# Generated by Django 5.0.3 on 2024-07-14 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0042_scholarship_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='logo',
        ),
    ]
