# Generated by Django 5.0.3 on 2024-07-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0044_scholarshipapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='ScholarshipApplication',
        ),
    ]
