# Generated by Django 5.0.3 on 2024-09-01 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0049_scholarshipapplication_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutEmpowering',
        ),
    ]
