# Generated by Django 5.0.3 on 2024-09-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0052_affordabilitysection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutEmpowering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('paragraph', models.TextField(blank=True, null=True)),
                ('application', models.TextField(blank=True, null=True)),
                ('university', models.TextField(blank=True, null=True)),
                ('accomodation', models.TextField(blank=True, null=True)),
                ('social', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_images/')),
            ],
        ),
    ]
