# Generated by Django 5.0.3 on 2024-09-01 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0054_uniplussection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UgProgramFirst',
        ),
    ]
