# Generated by Django 5.0.3 on 2024-09-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0056_degreesection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DegreeSection',
        ),
        migrations.DeleteModel(
            name='UgProgramSection',
        ),
    ]
