# Generated by Django 5.0.3 on 2024-09-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0059_coursesection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UgProgramInformation',
        ),
    ]
