# Generated by Django 5.0.3 on 2024-09-01 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0061_contactsection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UgImagesSection',
        ),
    ]
