# Generated by Django 5.0.3 on 2024-09-01 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0062_delete_ugimagessection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterContentSection',
        ),
    ]
