# Generated by Django 5.0.3 on 2024-09-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0064_masterdegreesection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MastersTaughtProgram',
        ),
    ]
