# Generated by Django 5.0.3 on 2024-09-01 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0066_programsection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MastersResearchProgram',
        ),
    ]
