# Generated by Django 5.0.3 on 2024-09-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0073_country_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='accommodation',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='university',
            name='location',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='university',
            name='ranking',
            field=models.TextField(default='none'),
        ),
    ]
