# Generated by Django 5.0.3 on 2024-09-11 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0074_university_accommodation_university_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_universities', to='uniplusprojectapp.university')),
            ],
        ),
    ]
