# Generated by Django 5.0.3 on 2024-09-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0075_topuniversity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship_page_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='degree_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='alumni_stories',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='other_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='types_of_awards',
            field=models.TextField(blank=True, null=True),
        ),
    ]
