# Generated by Django 5.0.3 on 2024-10-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0077_blogcard_author_blogcard_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcard',
            name='author',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
