# Generated by Django 5.0.3 on 2024-10-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0088_travel_assistance'),
    ]

    operations = [
        migrations.CreateModel(
            name='IELTSIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='ielts_images/')),
            ],
        ),
    ]
