# Generated by Django 5.0.3 on 2024-10-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0090_whychooseuniplus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('testimonial', models.TextField()),
                ('country', models.CharField(max_length=255)),
                ('exam_type', models.CharField(max_length=255)),
            ],
        ),
    ]
