# Generated by Django 5.0.3 on 2024-10-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0092_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content_images/'),
        ),
    ]
