# Generated by Django 5.0.3 on 2024-10-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0093_contentsection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='catrer_counselling',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='counselling_images/'),
        ),
    ]
