# Generated by Django 5.0.3 on 2024-10-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0094_catrer_counselling_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert_visa',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='expert_visa_images/'),
        ),
    ]
