# Generated by Django 5.0.3 on 2024-10-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0095_expert_visa_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_departure',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pre_departure_images/'),
        ),
    ]
