# Generated by Django 5.0.3 on 2024-10-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0096_pre_departure_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection_of_course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
