# Generated by Django 5.0.3 on 2024-10-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0097_selection_of_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel_assistance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='travel_assistance_images/'),
        ),
    ]
