# Generated by Django 5.0.3 on 2024-10-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0098_travel_assistance_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcard',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogcard',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
