# Generated by Django 5.0.3 on 2024-10-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0100_university_meta_description_university_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
