# Generated by Django 5.0.3 on 2024-10-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0101_scholarship_meta_description_scholarship_meta_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinUsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
    ]
