# Generated by Django 5.0.3 on 2024-10-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0102_joinuscontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduateStudySupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
    ]
