# Generated by Django 5.0.3 on 2024-10-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0104_lifeatuniplusimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ_join_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
    ]
