# Generated by Django 5.0.3 on 2024-10-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplusprojectapp', '0105_faq_join_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='remote',
            field=models.BooleanField(default=False),
        ),
    ]
